name: Write findings to CSV file

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *' # Run every hour at 00 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: create filename for findings file with current time & date
        run: | 
          echo "CURRENT_DATE=$(date +'%H-%M--%d-%m-%y')" >> $GITHUB_ENV
          echo "TMP=Findings" >> GITHUB_ENV
          echo "FILENAME=$($TMP-$CURRENT_DATE)" >> $GITHUB_ENV
      
      - name: Use Date Env Var
        run: |
          echo "$CURRENT_DATE"
          echo "$TMP"
          echo "$FILENAME"
          
      - name: execute py script # run main.py
        env:
          SEMGREP_API_WEB_TOKEN: ${{ secrets.SEMGREP_API_WEB_TOKEN }}

        run: python main.py

      - name: Upload findings as Artifact     
        uses: actions/upload-artifact@v3
        with:
          name: findings-csv
          path: output.csv
